# Generated by Django 4.2.1 on 2023-11-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
