# Generated by Django 4.2.1 on 2023-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='foto de perfil'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('TD', 'Director Técnico'), ('PR', 'Planillero'), ('FP', 'Jugador de Futboll'), ('CU', 'Usuario')], default='CU', max_length=2, verbose_name='tipo'),
        ),
    ]
