# Generated by Django 4.2.1 on 2023-09-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_system', '0002_person_profile_picture_alter_person_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='suspended',
        ),
        migrations.AddField(
            model_name='match',
            name='local_team_image',
            field=models.ImageField(blank=True, null=True, upload_to='match_images/'),
        ),
        migrations.AddField(
            model_name='match',
            name='visiting_team_image',
            field=models.ImageField(blank=True, null=True, upload_to='match_images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_system.club'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('TD', 'Director Técnico'), ('PR', 'Planillero'), ('CU', 'Usuario')], default='CU', max_length=2, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='PlayerSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('num_matches', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_system.player')),
            ],
            options={
                'verbose_name': 'Suspensión de Jugador',
                'verbose_name_plural': 'Suspensiones de Jugadores',
            },
        ),
        migrations.CreateModel(
            name='PlayerSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_system.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_system.player')),
            ],
            options={
                'verbose_name': 'Firma de Jugador',
                'verbose_name_plural': 'Firmas de Jugadores',
            },
        ),
    ]
