# Generated by Django 4.2.1 on 2023-11-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_system', '0002_player_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='local_team_goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='visiting_team_goals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
