# Generated by Django 4.2.1 on 2023-11-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_system', '0003_match_local_team_goals_match_visiting_team_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='images_processed',
            field=models.BooleanField(default=False),
        ),
    ]
