# Generated by Django 4.2.1 on 2023-09-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_system', '0003_remove_player_suspended_match_local_team_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerSignature',
        ),
    ]
