# Generated by Django 4.2.1 on 2023-09-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_system', '0004_delete_playersignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='recognition_local_team_image',
            field=models.ImageField(blank=True, null=True, upload_to='recognition_match_images/'),
        ),
        migrations.AddField(
            model_name='match',
            name='recognition_visiting_team_image',
            field=models.ImageField(blank=True, null=True, upload_to='recognition_match_images/'),
        ),
    ]
