# Generated by Django 4.2.1 on 2023-11-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_system', '0004_match_images_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
